version: '2'
services:
    family_doctor_server-app:
        image: family_doctor_server
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://family_doctor_server-mysql:3306/family_doctor_server?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    family_doctor_server-mysql:
        extends:
            file: mysql.yml
            service: family_doctor_server-mysql
